### ISSUE TITLE
[feature] 允许从系统字库当中设置自定义字体

### ISSUE THREAD

**Issue by Riajyuu** [li-zheng-hao/StickyNotes#1]
最好 UI 字体跟便签文本字体可以分别设置，当然如果像 VSC 那样，便签当中 CJK 字体跟英文字体分别设置就更好了

**Comment by ghost** [comment]
这个我觉得作为一个小软件其实没有很大必要去做这个项目，或者就默认字体为“电脑默认字体”就行。
例如：
A用户的电脑默认字体为“苹方”，则磁贴的字体为“苹方”。

**Comment by li-zheng-hao** [comment]
感觉这个需求不是很有必要，作为便签来说字体工整简洁应该就好了。

我觉得可以考虑找个好看的字体当默认的还挺不错的😀

**Comment by Riajyuu** [comment]
能找到是不错 但是font fallback是个大坑（除非只单一的考虑某一两个语系）
