### ISSUE TITLE
未知原因闪退

### ISSUE THREAD

**Issue by 6d6d** [li-zheng-hao/StickyNotes#11]
已安装完整基本运行库
未知原因启动时回闪退
![1](https://user-images.githubusercontent.com/57275657/74002236-6fd5dd00-4966-11ea-92c6-dc74ce31537d.png)
附上log
[debug.log](https://github.com/li-zheng-hao/StikyNotes/files/4169049/debug.log)

**Comment by li-zheng-hao** [comment]
什么系统？第一次启动就闪退吗？历史版本试过吗？

**Comment by 6d6d** [comment]
> 什么系统？第一次启动就闪退吗？历史版本试过吗？

刚试了下前一个版本没有问题，最新版本是第一次启动就闪退
系统是比较旧的windows 10 2016 ltsb
![image](https://user-images.githubusercontent.com/57275657/74012836-13cd8180-4983-11ea-9d97-80870cccd4b1.png)

**Comment by li-zheng-hao** [comment]
可能是系统版本的问题，可以尝试用兼容模式运行一下看看

**Comment by 6d6d** [comment]
> 可能是系统版本的问题，可以尝试用兼容模式运行一下看看

好的，已经可用
