### ISSUE TITLE
电脑重启后标签全部丢失

### ISSUE THREAD

**Issue by lu61488327** [li-zheng-hao/StickyNotes#12]
电脑重启后标签全部丢失，是否还能找回来？版本2.3.2

**Comment by li-zheng-hao** [comment]
数据存储在软件目录下的StikyNotesData.xml中，如果里面能找到就有，找不到就没了。
另外你电脑是正常重启吗？

**Comment by lu61488327** [comment]
Hi&nbsp;Li，


&nbsp; &nbsp; 谢谢您的回复，没有找到这个文件。你说正常重启的问题，我回想了当时的情况，可能是时间长了睡眠重启，还有可能是笔记本没电了掉电重启。因为这软件还是比较简单方便，所以用来还是比较顺手。
&nbsp; &nbsp; 我在想是否可以加入云服务，这样数据存储会不会更安全？&nbsp;而且收费也是可以接受的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LiZhengHao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月8日(星期天) 中午1:26
收件人:&nbsp;"li-zheng-hao/StikyNotes"<StikyNotes@noreply.github.com&gt;;
抄送:&nbsp;"61488327"<lu61488327@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [li-zheng-hao/StikyNotes] 电脑重启后标签全部丢失 (#12)




数据存储在软件目录下的StikyNotesData.xml中，如果里面能找到就有，找不到就没了。
 另外你电脑是正常重启吗？

**Comment by li-zheng-hao** [comment]
云服务会有数据隐私的问题，不方便把个人的数据放在我的服务器上。
等我后续加一个数据自动备份的功能，防止数据丢失，可以关注本项目等待下一次更新吧。

**Comment by li-zheng-hao** [comment]
@lu61488327 功能已修复，具体更新内容以及下载地址：[下载链接](https://github.com/li-zheng-hao/StikyNotes/releases/tag/v2.3.3)，可以从旧版本中直接复制StikyNotesData.xml文件到新项目中直接运行，数据可以无损迁移。
