### ISSUE TITLE
开机启动设置未成功

### ISSUE THREAD

**Issue by alekzander98** [li-zheng-hao/StickyNotes#13]
设置开机启动，但是重启后并没有成功，手动打开成功。

**Comment by li-zheng-hao** [comment]
系统版本是win10吗？
任务管理器中启动项这一行是“已启用”吗
![image](https://user-images.githubusercontent.com/22129824/77152726-76ae4e80-6ad3-11ea-8179-7d451e38641e.png)

**Comment by alekzander98** [comment]
是win10 在任务管理器中显示已启用 但程序并没有打开

**Comment by li-zheng-hao** [comment]
目录下的错误日志有啥内容不

**Comment by alekzander98** [comment]
log下有一个debug日志 每次手动打开会添加

**Comment by li-zheng-hao** [comment]
对，我就是说这个文件里有什么报错信息吗

**Comment by alekzander98** [comment]
这倒没有

**Comment by li-zheng-hao** [comment]
是不是开了360之类的东西？

**Comment by alekzander98** [comment]
解决了，谢谢 应该是火绒启动项的锅
