### ISSUE TITLE
清空%APPDATA%/Temp之后数据丢失

### ISSUE THREAD

**Issue by lbytony** [li-zheng-hao/StickyNotes#15]
清空%APPDATA%/Temp之后数据丢失，能否考虑将数据持久化存入安装的根目录。

**Comment by li-zheng-hao** [comment]
数据本身存储在安装根目录的`StikyNotesData.xml`文件中，关于你数据丢失的问题，先看一下该文件中数据是否还存在，不存在的话可以使用根目录下的`BackupData.xml`数据备份文件替换`StikyNotesData.xml`即可。

**Comment by lbytony** [comment]
`BackupData.xml`中我只看到了相关配置项的数据，比如字号、主题等，并没有发现存储的便签内容。

**Comment by li-zheng-hao** [comment]
那就是数据被清除了....我也不知道为啥会丢失数据，APPDATA文件下的东西还是别乱整比较好...
