### ISSUE TITLE
Win10蓝屏重启后，便利贴数据全没了

### ISSUE THREAD

**Issue by star-land** [li-zheng-hao/StickyNotes#16]
昨天Win10（企业版LTSC）突然蓝屏重启，系统启动后，便利贴自动启动，但数据都没了，貌似恢复了初始设置。

**Comment by li-zheng-hao** [comment]
用的是哪个版本呢？我前两天死机重启也出现了这样的情况，推测应该是退出软件保存数据的这一步在异常关机的情况下会出问题，新版本应该不会出现了

**Comment by star-land** [comment]
用的2.3.3版本

**Comment by li-zheng-hao** [comment]
换新版本试试

**Comment by star-land** [comment]
嗯嗯，已经换了 v3.1.1，继续支持
