### ISSUE TITLE
复制卡顿，剪切没效果

### ISSUE THREAD

**Issue by ymx5061004** [li-zheng-hao/StickyNotes#19]
win10 1067 64位系统

**Comment by li-zheng-hao** [comment]
软件什么版本？
我这测试v4.2.1操作很流畅，见下图：
![demo](https://user-images.githubusercontent.com/22129824/104719177-0b6ef080-5767-11eb-8de5-3f8de7d8bb7c.gif)

**Comment by ymx5061004** [comment]
任意版本，都有这个问题。
不过我系统已经升级，没有问题了
