### ISSUE TITLE
开机报错

### ISSUE THREAD

**Issue by diegojang** [li-zheng-hao/StickyNotes#23]
只有3.2.3版本的可以开机正常启动,最新的版本和4.2.1我都试过,开机就会报应用程序出错,然后退出,请问能解决吗?

**Comment by li-zheng-hao** [comment]
最新版本4.3.2，你可以再试试这个

**Comment by diegojang** [comment]
你好,

这个就是最新版的,我也试了,同样的问题哦. 😊



最新版本4.3.2，你可以再试试这个

—

**Comment by li-zheng-hao** [comment]
你下载的4.3.2版本压缩包里面的文件和下图是否一致？如果不一样再重下一次，一样的话看一下程序目录下`log`文件中报错信息是什么。
![image](https://user-images.githubusercontent.com/22129824/107000859-8efa8b00-67c3-11eb-9d61-a62f81ee9b12.png)

**Comment by diegojang** [comment]
你好,

一样的,其实我下过2次了,下过一次后出错,后来下了4.2.1,发觉文件多了很多,还以为下的有问题,然后又下了一边4.3.2,还是一样,因为一直出错,所以整个文件我已经删了,没了log了.我刚刚又重新来了遍.请看截图, 我现在用的3.2.3就没有问题.
![stikynotes1](https://user-images.githubusercontent.com/58846125/107013350-82ae0800-679a-11eb-9830-9cbbc11a27e0.png)

Log:
2021-02-05 10:07:04,845 INFO  - 程序启动
2021-02-05 10:07:24,728 INFO  - 程序退出
2021-02-05 10:08:36,094 INFO  - 程序启动
2021-02-05 10:08:36,630 ERROR -    在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 StikyNotes.MainViewModel.RestoreData(FlowDocument document, String fileName) 位置 D:\WPF\StikyNotes\StikyNotes\ViewModel\MainViewModel.cs:行号 138
   在 StikyNotes.App.OpenNewWindow(WindowsData data) 位置 D:\WPF\StikyNotes\StikyNotes\App.xaml.cs:行号 249
   在 StikyNotes.App.OnStartup(StartupEventArgs e) 位置 D:\WPF\StikyNotes\StikyNotes\App.xaml.cs:行号 67
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021-02-05 10:08:36,630 ERROR - 未能找到路径“C:\Windows\system32\Datas\2021-25-7-5-291”的一部分。

**Comment by diegojang** [comment]
请问能解决吗?

**Comment by li-zheng-hao** [comment]
报错信息提示的是软件启动的时候找不到你的数据:
C:\Windows\system32\Datas\2021-25-7-5-291
为什么你的数据会在这个路径下面，你看看你的软件放哪里的，再看看软件目录下面有没有Datas文件夹，里面有没有数据

**Comment by diegojang** [comment]
我的软件目录是放在c盘的user下面的download里面,不过system32下面没有datas这个目录,软件目录下面也没有. 

是不是我新建一个datas目录就能解决这个问题?

**Comment by li-zheng-hao** [comment]
别放桌面，找个d，f盘放软件试试

**Comment by diegojang** [comment]
> 别放桌面，找个d，f盘放软件试试

倒不是桌面,不过我今天放去D盘试试,谢谢

**Comment by diegojang** [comment]
> 别放桌面，找个d，f盘放软件试试

刚刚放在D盘根目录,试了,还是同样的错误,然后system32和软件目录下都添加了datas目录,也一样的错误

**Comment by li-zheng-hao** [comment]
加我微信lzh1263212577，这里回太慢了

**Comment by li-zheng-hao** [comment]
我刚试了一下在桌面创建快捷方式然后点快捷方式运行会导致这个问题，不知道你是不是这个原因。
等下个版本修复这个bug吧。

**Comment by li-zheng-hao** [comment]
测试了一下在下载目录下直接双击运行，关闭再打开不会报错。

**Comment by diegojang** [comment]
> 我刚试了一下在桌面创建快捷方式然后点快捷方式运行会导致这个问题，不知道你是不是这个原因。
> 等下个版本修复这个bug吧。

没有创建任何快捷方式,自己文件夹内exe运行, 另外,出错后,确实再打开没问题,但是只要重启,就会有这个问题.

没关系,我现在没空试了,就用3.2.3吧,先不加了,谢谢哦

**Comment by li-zheng-hao** [comment]
已修复，可以试一下

**Comment by diegojang** [comment]
> 已修复，可以试一下

好的,谢谢,我有空的时候试下,然后告诉你结果

**Comment by diegojang** [comment]
我试了几次,这个问题应该是被解决了,非常感谢
