### ISSUE TITLE
置顶后无法用快捷键隐藏

### ISSUE THREAD

**Issue by ghost** [li-zheng-hao/StickyNotes#32]
置顶后无法用快捷键隐藏
这一点太伤了
而且就算没置顶的时候，用快捷键隐藏响应很缓慢

**Comment by li-zheng-hao** [comment]
1. 置顶的东西不应该隐藏，我是这样认为的。
2. 响应缓慢的话，CPU内存什么配置？目前来说我还没遇到过卡顿的情况。

**Comment by ghost** [comment]
> 1. 置顶的东西不应该隐藏，我是这样认为的。
> 2. 响应缓慢的话，CPU内存什么配置？目前来说我还没遇到过卡顿的情况。

我解释一下我的使用场景：目前我是在对着视频学java，用你的便签软件记录了很多快捷键，当我用idea编程时，我希望便签置顶，方便我随时查看快捷键，当我结束编程时，我希望可以用快捷键方便的隐藏便签，因为我不需要了
关于响应慢，我的电脑是16G内存，AMD  R4000H，用便签的时候我电脑的状态很好，但就是响应慢
