### ISSUE TITLE
意外关机断电导致便签内容消失

### ISSUE THREAD

**Issue by golden777** [li-zheng-hao/StickyNotes#36]
意外关机断电导致便签内容消失
而且无法找回,就跟一些程序意外断电会导致配置文件丢失的问题一样

**Comment by golden777** [comment]
又丢了... 超频断电必丢...

**Comment by li-zheng-hao** [comment]
程序目录下的`BackupData.xml`文件里有数据吗？

**Comment by li-zheng-hao** [comment]
之前出这个问题的时候我加了一次2小时定时备份，应该是没问题的

**Comment by golden777** [comment]
那是要手动恢复?

**Comment by li-zheng-hao** [comment]
如果有数据的话就好说，用BackupData.xml文件替换一下StickyNotesData.xml再启动就可以了

目前还没加丢数据自动恢复的功能，后续有时间我再加上吧

**Comment by golden777** [comment]
OK,感谢
