### ISSUE TITLE
新版本开机自启动功能无法打开

### ISSUE THREAD

**Issue by rrrwing** [li-zheng-hao/StickyNotes#38]
1. autoupdate tool会显示“参数错误”然后程序自动退出，之后就再也打不开了，需要重新下载，同时还要在新的路径下才能正常运行
2. 4.6.1重新下载后，开机自动启动功能无法点击打开

**Comment by li-zheng-hao** [comment]
4.7.2版本测试过没问题，你手动下载升级试试

**Comment by li-zheng-hao** [comment]
发现bug原因了，4.7.3修复，这个需要手动下载一下新版本
