### ISSUE TITLE
开机自启动按钮点击依然没反应

### ISSUE THREAD

**Issue by rrrwing** [li-zheng-hao/StickyNotes#39]
自从更新到最新的两个版本之后，自开机功能一直都用不了。具体表现在点击自启动按钮，按钮没有反应，一直保持关闭状态。这个BUG删掉所有东西重新下载都无法修复。暂时不清楚是怎么触发的。

**Comment by li-zheng-hao** [comment]
1.管理员权限打开试试
2.任务管理器检查下启动界面是否有StickyNotes，如下图
![image](https://user-images.githubusercontent.com/22129824/154388098-a943f6a0-d0ca-4082-84e6-30f84488b1d3.png)

**Comment by li-zheng-hao** [comment]
确认了是有这个问题，下个版本修复

**Comment by li-zheng-hao** [comment]
修复完成，重启更新即可
