### ISSUE TITLE
自动跟随Windows主题色

### ISSUE THREAD

**Issue by Riajyuu** [li-zheng-hao/StickyNotes#42]
获取主题色的方法参考这里
https://github.com/File-New-Project/EarTrumpet/blob/d4acc41d5ac9dc4b5fb7d6165fe853d70c729940/EarTrumpet/Interop/Uxtheme.cs

监听变化的方法
https://docs.microsoft.com/en-us/windows/win32/gdi/wm-syscolorchange

**Comment by li-zheng-hao** [comment]
想法比较好，但是更换的话不是简单的更换RGB颜色，这个有时间再看
