### ISSUE TITLE
隐藏按钮无效，以及快捷键设置的问题

### ISSUE THREAD

**Issue by christaikobo** [li-zheng-hao/StickyNotes#48]
作者你好，感谢做了这么一个好用的程序！

我目前发现了2个问题，1是主界面上的那个“隐藏”按钮按了之后没有任何反应，在两台电脑，分别试了，都是一样的

2是，快捷键设置不能使用alt的组合键，而且不能使用任何一个单独的按键（个人觉得F9挺好用的！但是不能设置...）

**Comment by li-zheng-hao** [comment]
1. 用的什么版本？
2. 快捷键考虑重构，最近下班后看看有没有时间改吧

**Comment by christaikobo** [comment]
你好，用的是4.7.5

**Comment by li-zheng-hao** [comment]
刚看了一下代码，设置的逻辑是如果只有一个便利贴的情况下是隐藏不了的
