### ISSUE TITLE
[bug?] 关于窗口显示于最底层

### ISSUE THREAD

**Issue by Riajyuu** [li-zheng-hao/StickyNotes#9]
如图所示
![image](https://user-images.githubusercontent.com/16912240/67359375-a5acac80-f595-11e9-9202-82d5c4a9c5b5.png)

我不知道这是bug还是故意的。。。。

**Comment by li-zheng-hao** [comment]
应该是窗体设置了置顶，但是关于界面没置顶的原因，后续再改一下

**Comment by li-zheng-hao** [comment]
bug已修复，有问题可以再开新的issue @Riajyuu
